apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/barrypeng6/wordsmith.git
      targetRevision: HEAD
      path: k8s-manifests
    - repoURL: https://github.com/barrypeng6/wordsmith.git
      targetRevision: HEAD
      path: k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
