name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    name: Web Docker Build
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.TOKEN}}

      - name: 'Build & Push Web Image'
        run: |
          docker build ./web --tag ghcr.io/barrypeng6/wordsmith-web:v1.1
          docker push ghcr.io/barrypeng6/wordsmith-web:v1.1
      - name: 'Build & Push API Image'
        run: |
          docker build ./api --tag ghcr.io/barrypeng6/wordsmith-api:latest
          docker push ghcr.io/barrypeng6/wordsmith-api:latest